"""Keep only User and Comparison tables

Revision ID: 3e4ca81a6fd3
Revises: d5f6a269bdc2
Create Date: 2025-05-15 19:13:31.941514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4ca81a6fd3'
down_revision = 'd5f6a269bdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('team')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('avg_shots', sa.FLOAT(), nullable=False),
    sa.Column('avg_goals', sa.FLOAT(), nullable=False),
    sa.Column('avg_fouls', sa.FLOAT(), nullable=False),
    sa.Column('avg_cards', sa.FLOAT(), nullable=False),
    sa.Column('shot_accuracy', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
