"""Add recipient_id to ForumPost

Revision ID: 599baf44c3f6
Revises: 3e4ca81a6fd3
Create Date: 2025-05-16 20:23:17.924619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599baf44c3f6'
down_revision = '3e4ca81a6fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_forum_post_recipient_id_user', 'user', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forum_post_recipient_id_user', type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
