"""Initial migration: create User,EPL Team,EPL Comparison tables

Revision ID: d5f6a269bdc2
Revises: 
Create Date: 2025-05-15 17:39:41.606377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f6a269bdc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('avg_shots', sa.FLOAT(), nullable=False),
    sa.Column('avg_goals', sa.FLOAT(), nullable=False),
    sa.Column('avg_fouls', sa.FLOAT(), nullable=False),
    sa.Column('avg_cards', sa.FLOAT(), nullable=False),
    sa.Column('shot_accuracy', sa.FLOAT(), nullable=False),
    sa.Column('matched_team', sa.VARCHAR(length=80), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
